
@base = http://localhost:3001

### GET kaikki
GET {{base}}/api/transactions

### GET ei löydy (404)
GET http://localhost:3001/api/ei-ole

### Luo uusi
# @name createTx
POST {{base}}/api/transactions
Content-Type: application/json

{
  "paiva": "2025-10-08",
  "tyyppi": "myynti",
  "selite": "Testimyynti",
  "vastapuoli": "Testi Oy",
  "summa": 123.45,
  "maksettu": false
}

### Poista (käyttää edellä luodun vastauksen id:tä)
@id = {{createTx.response.body.$.id}}
DELETE {{base}}/api/transactions/{{id}}


### Päivitä maksettu (vaihda arvoa true/false)
PUT {{base}}/api/transactions/{{id}}
Content-Type: application/json

{
  "id": "21caa273-4d9b-4c4b-a98a-8664a9f01457",
  "paiva": "2025-10-08",
  "tyyppi": "myynti",
  "selite": "Testimyynti",
  "vastapuoli": "Testi Oy",
  "summa": 123.45,
  "maksettu": false
}

### (Valinnainen) virhetesti – 400 Bad Request
POST {{base}}/api/transactions
Content-Type: application/json

{
  "paiva": "",                 // puuttuu
  "tyyppi": "myynti",
  "selite": "Virheellinen",
  "summa": -10                 // virhe: ei > 0
}
