
@base = http://localhost:3001

### GET kaikki
GET {{base}}/api/transactions

### Luo uusi (tallenna vastaus, jotta voit käyttää id:tä myöhemmin)
# @name createTx
POST {{base}}/api/transactions
Content-Type: application/json

{
  "paiva": "2025-10-08",
  "tyyppi": "myynti",
  "selite": "Testimyynti",
  "vastapuoli": "Testi Oy",
  "summa": 123.45,
  "maksettu": false
}

### Poista (käyttää edellä luodun vastauksen id:tä)
@id = {{createTx.response.body.$.id}}
DELETE {{base}}/api/transactions/{{id}}


### Päivitä (muuta arvoja)
PUT {{base}}/api/transactions/{{id}}
Content-Type: application/json

{ "id": "3355e7ca-5929-4c6a-83c6-4e6f51d7b1b7",
  "paiva": "2025-10-08",
  "tyyppi": "myynti",
  "selite": "Testimyynti",
  "vastapuoli": "Testi Oy",
  "summa": 1210.45,
  "maksettu": false
}
